# Generated by Django 6.0.5 on 2026-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_latitude_attendance_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='selfie',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
