# Generated by Django 6.0.5 on 2026-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkout_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_selfies/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
